services:
  db:
    image: postgres:16.13
    container_name: workshop-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Ensure Postgres is fully initialized and accepting connections before other containers start
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:0.16.2
    container_name: workshop-pgweb
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      # Swapped deprecated 'DATABASE_URL' for 'PGWEB_DATABASE_URL'
      - PGWEB_DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: .
    container_name: workshop-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
