services:
  db:
    image: postgres:16.13
    container_name: workshop-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:0.16.2
    container_name: workshop-pgweb
    ports:
      - "8081:8081"
    environment:
      # We use 'db:5432' as host/port because containers connect via the internal Docker network.
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db

  backend:
    build: .
    container_name: workshop-backend
    ports:
      - "3000:3000"
    environment:
      # We override DATABASE_URL to connect to 'db:5432' inside the internal Docker network,
      # allowing the host to run locally or inside Docker seamlessly.
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    depends_on:
      - db

volumes:
  postgres-data:
